config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'homes#top'
  
 resources :users, only: [:index, :edit, :update]
 get 'users/account' => 'users#account', as: 'account'
 get 'users/profile' => 'users#profile', as: 'profile'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  
get 'rooms/posts' => 'rooms#posts', as: 'posts'
get 'rooms/search' => 'rooms#search'
resources :rooms, only: [:new, :index, :show, :create, :destroy, :update, :edit]

resources :reservations, only: [:new, :index, :show, :create, :destroy]
post 'reservations/confirm' => 'reservations#confirm', as: 'confirm'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
  attachment :profileimage
  
  has_many :rooms, dependent: :destroy
  has_many :reservations, dependent: :destroy
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
 before_action :move_to_signed_in
  
   def index
    @users = User.all
   end
   
   def account
    @user = current_user
   end
   
   def profile
    @user = current_user
   end
   
   def edit
    @user = current_user
   end
   
   def update
    @user = current_user
    @user.update(user_params)
    @user.update(profileimage: nil) if params[:image_delete].present? # 画像なしの場合に既存画像削除
    if @user.update(user_params)
     flash[:notice] = "ユーザー情報を更新しました"
     redirect_to profile_path
    else
     redirect_to root_path
    end
   end
   
   def user_params
    params.require(:user).permit(:name, :email, :profile, :profileimage, :encrypted_password)
   end
   
   def move_to_signed_in
    unless user_signed_in?
      #サインインしていないユーザーはログインページが表示される
      redirect_to  '/users/sign_in'
    end
   end
   
end

app/views/users/account.html.erb
<div class="row">
  <div class="col-2">
      <%= render "users/shared/bubun" %>
  </div>
  
<div class="col-10">
<div class="out">
 <div class="in">
  <h3>アカウント</h3>
   <table class="acounttable">
    <tbody>
     <tr>
      <th>メールアドレス</th>
      <td><%= @user.email %></td>
     </tr>
     <tr>
      <th>パスワード</th>
      <td>*********</td>
     </tr>
     <tr>
      <th><%= link_to '編集する', edit_user_registration_path, class: 'btn btn-primary', data: {"turbolinks"=>false} %></th>
      <td></td>
     </tr>
    </tbody>
   </table>
 </div>
 </div>
 
</div>
</div>
  

app/views/users/edit.html.erb
<div class="row">
  <div class="col-4">
  </div>

<div class="editview">
 <h3>アカウント編集</h3>
<table>
 <tbody>
  <%= form_with model:@user, url: user_path(@user), local: true do |f| %>
  <tr>
   <td><%= f.label :メールアドレス %></td>
  </tr>
  <tr>
   <td><%= f.email_field :email, autofocus: true, autocomplete: "email", maxlength: "50", size: "50" %></td>
  </tr>
  <tr>
   <td><%= f.label :変更後パスワード（変更する場合のみ入力） %></td>
  </tr>
  <tr>
   <td><%= f.password_field :password, autofocus: true, autocomplete: "new-password", maxlength: "50", size: "50" %></td>
  </tr> 
  <tr>
   <td><%= f.label :パスワード確認用（変更する場合のみ入力）%></td>
  </tr>
  <tr>
   <td><%= f.password_field :password_confirmation, autocomplete: "new-password", maxlength: "50", size: "50" %></td>
  </tr>
  <tr>
   <td><%= f.label :現在のパスワード）%></td>
  </tr>
  <tr>
   <td><%= f.password_field :current_password, autocomplete: "current-password", maxlength: "50", size: "50" %></td>
  </tr>
  <tr>
   <td><%= f.submit "更新", class: 'btn btn-primary' %></td>
  <% end %>
  </tr>
  <tr>
   <td><%= link_to '戻る', account_path, class: "btn btn-outline-primary" %></td>
  </tr>
 </tbody>
</table>
</div>
</div>

app/views/users/index.html.erb
<%= render "users/shared/bubun" %>

<div>
<h3>ユーザー一覧</h3>

 <table>
  <tr>
   <th>id</th>
   <th>名前</th>
   <th>メールアドレス</th>
   <th>パスワード</th>
   <th>パスワード</th>
   <th>自己紹介</th>
   <th>アイコン画像</th>
  </tr>
  <% @users.each do |user| %>
  <tr>
   <td><%= user.id %></td>  
   <td><%= user.name %></td> 
   <td><%= user.email %></td>
   <td><%= user.password %></td>
   <td><%= user.encrypted_password %></td>
   <td><%= user.profile %></td>
   <td><%= attachment_image_tag user, :profileimage, fallback: "no_image_logo.png", size: '80x80' %></td>
   <td><%= link_to '削除する', user_path(user), method: :delete, class: 'btn btn-danger', data: { confirm: "本当に削除しますか？" }%></td>
   </tr>
   <% end %>
 </table>
 </div>

app/views/users/profile.html.erb
<div class="row">
  <div class="col-2">
   <%= render "users/shared/bubun" %>
  </div>

<div class="col-10">
<div class="out">
 <div class="in">
 <h3>プロフィール</h3>
  <table class="profiletable">
   <tbody>
    <tr>
     <th></th>
     <th></th>
     <td><%= attachment_image_tag @user, :profileimage, fallback: "no_image_logo.png", size: '80x80', class: "aicon" %></td>
    </tr>
    <%= form_with model:@user, url: user_path(@user), local: true do |f| %>
     <tr>
      <th><%= f.label :アイコン画像 %></th>
      <th><div class="aa">必須</div></th>
      <td>
        <label><%= check_box_tag :image_delete %>画像なし</label>
        <label><%= f.attachment_field :profileimage %></label>
      </td>
     </tr>
    <tr>
     <th><%= f.label :名前 %></th>
     <th><div class="aa">必須</div></th>
     <td><%= f.text_field :name, autofocus: true, required: true, class: 'form-control', maxlength: "40", size: "40" %></td>
    </tr>
    <tr>
     <th><%= f.label :自己紹介 %></th>
     <th><div class="aa">必須</div></th>
     <td><%= f.text_area :profile, autofocus: true, class: 'form-control', size: '40x5' %></td>
    </tr>
    <tr>
     <th><%= f.submit "更新する", class: 'btn btn-primary' %></th>
     <th></th>
     <td></td>
    <% end %>
    </tr>
   </tbody>
  </table>
 </div>
</div>
</div>
 
</div>