config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'homes#top'
  
 resources :users, only: [:index, :edit, :update]
 get 'users/account' => 'users#account', as: 'account'
 get 'users/profile' => 'users#profile', as: 'profile'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  
get 'rooms/posts' => 'rooms#posts', as: 'posts'
get 'rooms/search' => 'rooms#search'
resources :rooms, only: [:new, :index, :show, :create, :destroy, :update, :edit]

resources :reservations, only: [:new, :index, :show, :create, :destroy]
post 'reservations/confirm' => 'reservations#confirm', as: 'confirm'

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  
  belongs_to :user
  belongs_to :room
  
  validates :startdate, presence: true
  validates :enddate, presence: true
  validates :human, presence: true, numericality: { less_than_or_equal_to: 20, greater_than_or_equal_to: 1 }
  validate :start_end_check
  validate :date_before_start

  def start_end_check
    errors.add(:enddate, "は開始日以降の日を登録してください") unless
    startdate == nil or enddate == nil or startdate < enddate
  end
  
  def date_before_start
    errors.add(:startdate, "は今日以降のものを選択してください") if  startdate != nil and enddate != nil and startdate < Date.today
  end
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  
  before_action :move_to_signed_in
  
  def index
    @reservations = Reservation.all.order(updated_at: 'ASC').page(params[:page]).per(4)
  end
  
  def new
    @reservation = Reservation.new
  end
  
  def confirm
    @reservation = Reservation.new(reservation_params)
    if @reservation.valid? # バリデーションを手動でチェック
      @reservation.totalprice = (@reservation.enddate - @reservation.startdate).to_int * @reservation.human * @reservation.price
      render "confirm"
    else
      @room = Room.find(@reservation.room_id)
      render 'rooms/show'
    end
  end
  
  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.usedate = @reservation.enddate - @reservation.startdate
    if @reservation.save
      flash[:notice] = "予約新規登録しました"
      redirect_to reservation_path(@reservation)
    else
      redirect_to root_path
    end
  end
  
  def show
    @reservation = Reservation.find(params[:id])
  end
  
  def destroy
    reservation = Reservation.find(params[:id])
    reservation.user_id = current_user.id
    reservation.destroy
    flash[:notice] = "削除しました"
    redirect_back(fallback_location: root_path)
  end
  
  def reservation_params
    params.require(:reservation).permit(:human, :startdate, :enddate, :room_id, :user_id, :price, :totalprice)
  end
  
  def move_to_signed_in
    unless user_signed_in?
      #サインインしていないユーザーはログインページが表示される
      redirect_to  '/users/sign_in'
    end
  end
  
end

app/views/reservations/_new.html.erb
  <%= render "shared/error", obj: @reservation %>
  
  
  <table class="acounttable">
   <tbody>
    <%= form_with model: @reservation, url: confirm_path, method: :post, local: true do |f| %>
    <tr>
     <td><%= f.label :startdate ,"開始日" %>
         <%= f.date_field :startdate, autofocus: true, class: 'form-control' %>
      </td>
    </tr>
    <tr>
     <td><%= f.label :enddate ,"終了日" %>
         <%= f.date_field :enddate, class: 'form-control' %>
     </td>
    </tr>
    <tr>
     <td><%= f.label :使用人数 %>
         <%= f.number_field :human, class: 'form-control' %>
     </td>
    </tr>
    <% if user_signed_in? %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :room_id, :value => @room.id %>
    <%= f.hidden_field :price, :value => @room.price %>
    <tr>
     <td><%= f.submit "確認画面へ進む", class: 'btn btn-primary', data: {"turbolinks"=>false} %></td>
    </tr>
    <% else %>
    <tr>
     <td><%= link_to 'ログイン', new_user_session_path, class: 'btn btn-primary' %></td>
    </tr>
    <% end %>
    <% end %>
   </tbody>
  </table>

app/views/reservations/confirm.html.erb
<div class="container">
 <div class="row">
  <div class="col-3">
 </div>
 
 <div class="col-6">
 <table class="acounttable">
   <tbody>
    <tr>
     <td><h3>予約内容確認</h3></td>
    </tr>
    <tr>
     <td><h3>￥<%= @reservation.price %>/日</h3></td>
    </tr>
    <%= form_with(model: @reservation, local: true) do |f| %>
    <tr>
     <td>開始日<%= f.hidden_field :startdate, :value => @reservation.startdate %>
     <%= f.date_field :startdate, class: 'form-control', :readonly => true %>
     </td>
    </tr>
    <tr>
     <td>終了日<%= f.hidden_field :enddate, :value => @reservation.enddate %>
        <%= f.date_field :enddate, class: 'form-control', :readonly => true %>
     </td>
    </tr>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :room_id, :value => @reservation.room_id %>
    <tr>
     <td>□使用日数:<%= (@reservation.enddate - @reservation.startdate).to_int %>日</td>
    </tr>
    <tr>
     <td><%= f.hidden_field :human, :value => @reservation.human %>□人数:<%= @reservation.human %>人</td>
    </tr>
    <tr>
     <td>合計金額<%= f.hidden_field :totalprice, :value => @reservation.totalprice %>
     <%= f.number_field :totalprice, class: 'form-control', :readonly => true %>
     </td>
    </tr>
    <tr>
     <td>上記内容でよろしければ「予約を確定」を押してください</td>
    </tr>
    <tr>
     <td><%= f.submit "予約を確定", class: 'btn btn-primary', data: {"turbolinks"=>false} %></td>
    </tr>
    <tr>
     <td><%= link_to 'ルーム詳細に戻る', room_path(@reservation.room_id), class: "btn btn-secondary", data: {"turbolinks"=>false} %></td>
    </tr>
    <% end %>
   </tbody>
  </table>
  </div>
  
  </div>
</div>

app/views/reservations/index.html.erb
<h3>予約済みルーム一覧</h3>

 <table class="posttable">
  <tr>
   <th>ルーム画像</th>
   <th>ルーム名</th>
   <th>ルーム紹介</th>
   <th>合計料金</th>
   <th>開始日</th>
   <th>終了日</th>
   <th>予約確定日時</th>
   <th></th>
  </tr>
  <%= paginate @reservations %>
  <% @reservations.each do |reservation| %>
  <tr>
   <td><%= link_to attachment_image_tag( reservation.room, :roomimage, fallback: "no_image_logo.png", size: '240x140'), room_path(reservation.room_id), data: {"turbolinks"=>false} %></td>
   <td><%= link_to reservation.room.roomname, room_path(reservation.room_id), data: {"turbolinks"=>false} %></td>
   <td><%= reservation.room.roomprofile %></td>
   <td>￥<%= reservation.totalprice %></td>
   <td><%= reservation.startdate.strftime("%Y年 %m月 %d日")  %></td>
   <td><%= reservation.enddate.strftime("%Y年 %m月 %d日")  %></td>
   <td><%= reservation.created_at.to_s(:datetime_jp) %></td>
   <% if current_user.id == reservation.user_id %>
   <td><%= link_to '削除する', reservation_path(reservation), method: :delete, class: 'btn btn-danger', data: { confirm: "本当に削除しますか？" } %></td>
   <% end %>
  </td>
   <% end %>
   
 </table>

app/views/reservations/show.html.erb
<h2>予約内容画面</h2>

<div class="complete">
 <div class="in">
 <table class="reservationtable">
  <tr>
   <th>予約した部屋</th>
   <td><%= @reservation.room.roomname %></td>
  </tr>
  <tr>
   <th>開始日</th>
   <td><%= @reservation.startdate.strftime("%Y年 %m月 %d日") %></td>
  </tr>
  <tr>
   <th>終了日</th>
   <td><%= @reservation.enddate.strftime("%Y年 %m月 %d日") %></td>
  </tr>
  <tr>
   <th>人数</th>
   <td><%= @reservation.human %>人</td>
  </tr>
  <tr>
   <th>価格</th>
   <td><%= @reservation.totalprice %>円</td>
  </tr>
  <tr>
   <th>使用日数</th>
   <td><%= @reservation.usedate %>日</td>
  </tr>
 </table>
 
 </div>
 </div>