config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'homes#top'
  
 resources :users, only: [:index, :edit, :update]
 get 'users/account' => 'users#account', as: 'account'
 get 'users/profile' => 'users#profile', as: 'profile'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  
get 'rooms/posts' => 'rooms#posts', as: 'posts'
get 'rooms/search' => 'rooms#search'
resources :rooms, only: [:new, :index, :show, :create, :destroy, :update, :edit]

resources :reservations, only: [:new, :index, :show, :create, :destroy]
post 'reservations/confirm' => 'reservations#confirm', as: 'confirm'

end

app/views/layouts/_footer.html.erb
<footer>
     <p>© 2020 POTEPAN.INC.</p>
</footer>

app/views/layouts/_header.html.erb
<header>
 <div class="hed">
  <%= link_to image_tag("logo.png"), root_path, data: {"turbolinks"=>false} %>
  <div class="areaaicon">
   <%= form_with url: rooms_search_path, method: :get, local: true do |f| %>
     <%= f.text_field :area, value: @area, :placeholder => "エリア", size:'20x10' %>
   <% end %>
  </div>
  <div class="keywordaicon">
   <%= form_with url: rooms_search_path, method: :get, local: true do |f| %>
     <%= f.text_field :keyword, value: @keyword, :placeholder => "キーワード", size:'20x10' %>
   <% end %>
  </div>
  <div class="user">
   <% if user_signed_in? %>
    <%= current_user.name %>
     <a data-toggle="dropdown" ><%= attachment_image_tag current_user, :profileimage, fallback: "no_img.png", size: '60x60', class: "aicon" %></a>
     <ul class="dropdown-menu">
      <li><%= link_to 'ルーム登録', new_room_path, class: 'link', data: {"turbolinks"=>false} %></li>
      <li><%= link_to '予約済みルーム一覧', reservations_path, class: 'link', data: {"turbolinks"=>false} %></li> 
      <li><%= link_to '登録済みルーム一覧', posts_path, class: 'link', data: {"turbolinks"=>false} %></li>
      <li><%= link_to '設定', account_path, class: 'link', data: {"turbolinks"=>false} %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'link' %></li>
     </ul>
   <% else %>
    <div class="loginaicon">
     <%= link_to 'ログイン', new_user_session_path, class: 'btn btn-primary' %>
     <%= link_to '登録する', new_user_registration_path, class: 'btn btn-secondary' %>
    </div>
   <% end %>
  </div>
 </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- コード追加　Bootstrap CSS読み込みコード-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- コード追加　Bootstrap JavaScript読み込みコード-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
  </head>
<body>
   <%= render 'layouts/header' %>
   <main class="main"> 
   <% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
 <% end %>
     <%= yield %> 
   </main>
 
   <%= render 'layouts/footer' %>
   
  </body>
</html>

app/views/layouts/sub-layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- コード追加　Bootstrap CSS読み込みコード-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- コード追加　Bootstrap JavaScript読み込みコード-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
  </head>
<body>
   <%= render 'layouts/header' %>
 <main class="main2"> 
   <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
   <% end %>
     <%= yield %> 
   </main>
    <footer class="footer2"> 
     <p>© 2020 POTEPAN.INC.</p>
    </footer> 
  </body>
</html>